### ISSUE TITLE
执行./kongyixueyuan时候报错以下内容

### ISSUE THREAD

**Issue by zhangzhao2** [kevin-hf/kongyixueyuan#3]
link@link-All-Series:~/go/src/github.com/kongyixueyuan.com/kongyixueyuan$ ./kongyixueyuan 
panic: mismatching message name: got msp.SerializedIdentity, want sdk.msp.SerializedIdentity

goroutine 1 [running]:
github.com/kongyixueyuan.com/kongyixueyuan/vendor/google.golang.org/protobuf/internal/impl.legacyLoadMessageDesc(0xd37220, 0xbe1c80, 0xc9ad48, 0x1a, 0x0, 0x0)
	/home/link/go/src/github.com/kongyixueyuan.com/kongyixueyuan/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:136 +0x8c1
github.com/kongyixueyuan.com/kongyixueyuan/vendor/google.golang.org/protobuf/internal/impl.legacyLoadMessageInfo(0xd37220, 0xbe1c80, 0xc9ad48, 0x1a, 0x11c8400)
	/home/link/go/src/github.com/kongyixueyuan.com/kongyixueyuan/vendor/google.golang.org/protobuf/internal/impl/legacy_message.go:48 +0xbf
github.com/kongyixueyuan.com/kongyixueyuan/vendor/google.golang.org/protobuf/internal/impl.Export.LegacyMessageTypeOf(0xd28000, 0x0, 0xc9ad48, 0x1a, 0xc4200b3e30, 0x40ce35)
	/home/link/go/src/github.com/kongyixueyuan.com/kongyixueyuan/vendor/google.golang.org/protobuf/internal/impl/legacy_export.go:33 +0xa5
github.com/kongyixueyuan.com/kongyixueyuan/vendor/github.com/golang/protobuf/proto.RegisterType(0xd28000, 0x0, 0xc9ad48, 0x1a)
	/home/link/go/src/github.com/kongyixueyuan.com/kongyixueyuan/vendor/github.com/golang/protobuf/proto/registry.go:186 +0x53
github.com/kongyixueyuan.com/kongyixueyuan/vendor/github.com/hyperledger/fabric-sdk-go/third_party/github.com/hyperledger/fabric/protos/msp.init.0()
	/home/link/go/src/github.com/kongyixueyuan.com/kongyixueyuan/vendor/github.com/hyperledger/fabric-sdk-go/third_party/github.com/hyperledger/fabric/protos/msp/identities.pb.go:142 +0x4e

**Comment by zhangzhao2** [comment]
麻烦韩老师看到给解决一下，网上搜索了各种办法都没有解决

**Comment by zhangzhao2** [comment]
麻烦韩老师看到给解决一下，网上搜索了各种办法都没有解决

**Comment by MJLee00** [comment]
same problem:
panic: mismatching message name: got msp.SerializedIdentity, want sdk.msp.SerializedIdentity

**Comment by houjibofa2050** [comment]
我也遇到上面的问题，韩老师帮忙看一下
